- project:
    queue: murano
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - murano-tempest-api:
            voting: false
        - murano-tempest-api-zed:
            voting: false
        - murano-tempest-api-yoga:
            voting: false
        - murano-tempest-api-xena:
            voting: false
        - murano-tempest-api-wallaby:
            voting: false
        - murano-tempest-cfapi

- job:
    name: murano-tempest-api-zed
    parent: murano-tempest-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: murano-tempest-api-yoga
    parent: murano-tempest-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- job:
    name: murano-tempest-api-xena
    parent: murano-tempest-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- job:
    name: murano-tempest-api-wallaby
    parent: murano-tempest-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
