- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - murano-tempest-api:
            voting: false
        - murano-tempest-api-ussuri:
            voting: false
        - murano-tempest-api-train:
            voting: false
        - murano-tempest-api-stein:
            voting: false
        - murano-tempest-cfapi
    gate:
      queue: murano

- job:
    name: murano-tempest-api-ussuri
    parent: murano-tempest-api
    override-checkout: stable/ussuri

- job:
    name: murano-tempest-api-train
    parent: murano-tempest-api
    override-checkout: stable/train

- job:
    name: murano-tempest-api-stein
    parent: murano-tempest-api
    override-checkout: stable/stein
