- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - murano-tempest-api:
            voting: false
        - murano-tempest-api-wallaby:
            voting: false
        - murano-tempest-api-victoria:
            voting: false
        - murano-tempest-api-ussuri:
            voting: false
        - murano-tempest-api-train:
            voting: false
        - murano-tempest-cfapi
    gate:
      queue: murano

- job:
    name: murano-tempest-api-wallaby
    parent: murano-tempest-api
    override-checkout: stable/wallaby

- job:
    name: murano-tempest-api-victoria
    parent: murano-tempest-api
    override-checkout: stable/victoria

- job:
    name: murano-tempest-api-ussuri
    parent: murano-tempest-api
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri

- job:
    name: murano-tempest-api-train
    parent: murano-tempest-api
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
